# 本文件的意义是：
#   1. 本地热启动时不加载耗时过多的插件
#   2. 自定义一些试验中的额外样式和脚本
# 启动命令：
#   1. 最简启动：mkdocs serve -f local.yml
#   2. 完整启动：mkdocs serve -f mkdocs.yml
#   3. 最快启动：zensical serve -f mkdocs.yml


# 继承功能，MkDocs 独有
INHERIT: mkdocs.yml

plugins:
  - meta
  - search
  - glightbox:
      auto_caption: false
  - toggle-sidebar:
      theme: material
      toggle_button: all
      button_toggle_both_tooltip: 折叠或展开文件列表和页面目录

watch:
  - mkdocs.yml
  - overrides/
