# MkDocs 提供 yaml 文件的继承功能
# 启动命令：
#   mkdocs serve -q -f ./local.yml
# 本文件的意义是：
#   1. 本地热启动时不加载耗时过多的插件
#   2. 自定义一些试验中的额外样式和脚本

INHERIT: ./mkdocs.yml

plugins:
  - meta
  - search
  - glightbox:
      auto_caption: false
  - toggle-sidebar:
      theme: material
      toggle_button: all
      button_toggle_both_tooltip: 折叠或展开文件列表和页面目录

watch:
  - mkdocs.yml
  - overrides/
